name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - name: Install dependencies
        run: |
          python -m pip install ---upgrade pip
          pip install -r requirements.txt

      - name: Build with pyinstaller for windows
        run: pyinstaller --clean -y --dist ./dist/windows --workpath /tmp audio_switcher.spec

      - uses: actions/upload-artifact@v3
        with:
          name: dist-windows
          path: dist/windows

  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: create release draft
        id: create_draft
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
